# Generated by Django 6.0.3 on 2026-03-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=9999)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('activity_type', models.CharField(blank=True, max_length=100)),
                ('materials_needed', models.TextField(blank=True)),
                ('variants', models.TextField(blank=True)),
                ('notes_for_facilitator', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('internal_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['internal_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('minutes_per_session', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=9999)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.agegroup')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.language')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('grammar_objectives', models.TextField(blank=True)),
                ('action_objectives', models.TextField(blank=True)),
                ('lexical_objectives', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='curriculum.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_topics', to='curriculum.topic')),
            ],
            options={
                'ordering': ['course', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopicGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_topic', models.PositiveIntegerField()),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('course_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_games', to='curriculum.coursetopic')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_topic_games', to='curriculum.game')),
            ],
            options={
                'ordering': ['course_topic', 'order_in_topic'],
                'constraints': [models.UniqueConstraint(fields=('course_topic', 'order_in_topic'), name='unique_course_topic_game_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.UniqueConstraint(fields=('course', 'sequence_number'), name='unique_course_sequence_number'),
        ),
    ]
