# Generated by Django 6.0.3 on 2026-03-17 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopicPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_in_topic', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['course_topic', 'order_in_topic', 'translation__text'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopicVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_in_topic', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['course_topic', 'order_in_topic', 'translation__word'],
            },
        ),
        migrations.CreateModel(
            name='PhraseConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_key', models.SlugField(max_length=255, unique=True)),
                ('phrase_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['concept_key'],
            },
        ),
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airtable_record_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('text', models.TextField()),
                ('phonetic', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_file_url', models.URLField(blank=True)),
                ('audio_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_key', models.SlugField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['concept_key'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airtable_record_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('phonetic', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_file_url', models.URLField(blank=True)),
                ('audio_status', models.CharField(blank=True, max_length=50)),
                ('flashcard_pdf_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ['course', 'sequence_number', 'title']},
        ),
        migrations.AlterModelOptions(
            name='coursetopicgame',
            options={'ordering': ['course_topic', 'order_in_topic', 'id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='coursetopic',
            name='unique_course_sequence_number',
        ),
        migrations.RemoveConstraint(
            model_name='coursetopicgame',
            name='unique_course_topic_game_order',
        ),
        migrations.RemoveField(
            model_name='game',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='notes_for_facilitator',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='internal_name',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agegroup',
            name='education_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='age_group_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='card_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursetopicgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetopicgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='main_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='display_order',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.agegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_topics', to='curriculum.topic'),
        ),
        migrations.AlterField(
            model_name='coursetopicgame',
            name='order_in_topic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.UniqueConstraint(fields=('course', 'sequence_number'), name='unique_course_topic_sequence_per_course'),
        ),
        migrations.AddConstraint(
            model_name='coursetopicgame',
            constraint=models.UniqueConstraint(fields=('course_topic', 'order_in_topic'), name='unique_game_order_per_course_topic'),
        ),
        migrations.AddField(
            model_name='coursetopicphrase',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_phrases', to='curriculum.coursetopic'),
        ),
        migrations.AddField(
            model_name='coursetopicvocabulary',
            name='course_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_vocabulary', to='curriculum.coursetopic'),
        ),
        migrations.AddField(
            model_name='phraseconcept',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrase_concepts', to='curriculum.topic'),
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='curriculum.phraseconcept'),
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrase_translations', to='curriculum.language'),
        ),
        migrations.AddField(
            model_name='coursetopicphrase',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_links', to='curriculum.phrasetranslation'),
        ),
        migrations.AddField(
            model_name='vocabularyconcept',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_concepts', to='curriculum.topic'),
        ),
        migrations.AddField(
            model_name='vocabularytranslation',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='curriculum.vocabularyconcept'),
        ),
        migrations.AddField(
            model_name='vocabularytranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_translations', to='curriculum.language'),
        ),
        migrations.AddField(
            model_name='coursetopicvocabulary',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topic_links', to='curriculum.vocabularytranslation'),
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='teacher_notes',
        ),
        migrations.RemoveField(
            model_name='coursetopicgame',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='coursetopicgame',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='coursetopicgame',
            name='stage_name',
        ),
        migrations.RemoveField(
            model_name='coursetopicgame',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='phrasetranslation',
            constraint=models.UniqueConstraint(fields=('concept', 'language'), name='unique_phrase_translation_per_language'),
        ),
        migrations.AddConstraint(
            model_name='coursetopicphrase',
            constraint=models.UniqueConstraint(fields=('course_topic', 'translation'), name='unique_phrase_translation_per_course_topic'),
        ),
        migrations.AddConstraint(
            model_name='vocabularytranslation',
            constraint=models.UniqueConstraint(fields=('concept', 'language'), name='unique_vocabulary_translation_per_language'),
        ),
        migrations.AddConstraint(
            model_name='coursetopicvocabulary',
            constraint=models.UniqueConstraint(fields=('course_topic', 'translation'), name='unique_vocabulary_translation_per_course_topic'),
        ),
    ]
