# Generated by Django 6.0.3 on 2026-03-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_coursetopicphrase_coursetopicvocabulary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='age_group_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sessions_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='language',
            name='status',
        ),
        migrations.RemoveField(
            model_name='phraseconcept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='audio_file_url',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='audio_status',
        ),
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='vocabularyconcept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='airtable_record_id',
        ),
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='audio_file_url',
        ),
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='audio_status',
        ),
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.agegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
