# Generated by Django 6.0.3 on 2026-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_agegroup_airtable_record_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasetranslation',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/phrases/'),
        ),
        migrations.AddField(
            model_name='vocabularytranslation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/vocabulary/'),
        ),
    ]
