# Generated by Django 6.0.3 on 2026-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_phrasetranslation_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
