# Generated by Django 6.0.3 on 2026-03-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_course_card_image_alter_game_main_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularytranslation',
            name='flashcard_pdf_url',
        ),
        migrations.AddField(
            model_name='course',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabularytranslation',
            name='flashcard_pdf',
            field=models.FileField(blank=True, null=True, upload_to='flashcards/vocabulary/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curriculum.agegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='status',
            field=models.CharField(blank=True, default='published', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, default='published', max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(blank=True, default='published', max_length=50),
        ),
    ]
