# Generated by Django 6.0.3 on 2026-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_vocabularytranslation_flashcard_pdf_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='flag',
        ),
        migrations.AddField(
            model_name='language',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='languages/flags/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
