# Generated by Django 6.0.3 on 2026-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_remove_language_flag_language_flag_emoji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='flag_emoji',
        ),
        migrations.RemoveField(
            model_name='language',
            name='flag_image',
        ),
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.CharField(blank=True, default='🌍', max_length=10),
        ),
    ]
