# Generated by Django 6.0.3 on 2026-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_remove_language_flag_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='games', to='curriculum.topic'),
        ),
    ]
