# Generated by Django 6.0.3 on 2026-03-12 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_city_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classparticipation',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='joined_class_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classparticipation',
            name='other_volunteers',
            field=models.ManyToManyField(blank=True, related_name='legacy_other_class_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classparticipation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_main_class_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
