# Generated by Django 6.0.3 on 2026-03-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_teacherschoolmembership'),
        ('users', '0003_classparticipation_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classparticipation',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='schools.classroom'),
        ),
        migrations.AddField(
            model_name='classparticipation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_participations', to='schools.school'),
        ),
    ]
