# Generated by Django 6.0.3 on 2026-03-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_vocabularytranslation_flashcard_pdf_url_and_more'),
        ('schools', '0002_teacherschoolmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='curriculum.course'),
        ),
    ]
