# Generated by Django 6.0.3 on 2026-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_classroom_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='schools/covers/'),
        ),
    ]
